ARCHITECTURE=riscv64
QEMU_MACHINE=k3-pico-itx
RELEASE_ASSET_PREFIX=riscv64-k3-pico-itx
REQUIRED_IMAGES=(
    fw_dynamic.bin
    u-boot.bin
    k3-pico-itx-qemu-uboot.dtb
    k3-qemu-sd.raw
)
FUNCTIONAL_IMAGES=(
    Image
    fw_dynamic.bin
    k3-qemu-initramfs.cpio.gz
    k3-pico-itx-qemu.dtb
    u-boot.bin
    k3-pico-itx-qemu-uboot.dtb
    k3-qemu-sd.raw.xz
    eweos-k3-initramfs.cpio.gz
)
